<a href="https://colab.research.google.com/github/MengOonLee/BertelsmannAITrack/blob/Lesson05/MultilayerNeuralNetworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# First import PyTorch
import torch
torch.cuda.is_available()

True

In [0]:
def activation(x):
  """ Sigmoid activation function
    Arguments
    x: torch.Tensor
  """
  return 1/(1+torch.exp(-x))

In [3]:
# Generate some data
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1,3))
print("features =", features)
print("features shape =", features.shape)

# Define the size of each layer in network
n_input = features.shape[1]
n_hidden = 2
n_output = 1
print("Number of input =", n_input, "\nNumber of hidden units =", n_hidden, "\nNumber of output =", n_output)

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
print("Weights for H1 =", W1)
print("W1 shape =", W1.shape)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)
print("Weights for H2 =", W2)
print("W2 shape =", W2.shape)

# and bias teams for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))
print("Bias for H1 =", B1)
print("B1 shape =", B1.shape)
print("Bias for H2 =", B2)
print("B2 shape =", B2.shape)

features = tensor([[-0.1468,  0.7861,  0.9468]])
features shape = torch.Size([1, 3])
Number of input = 3 
Number of hidden units = 2 
Number of output = 1
Weights for H1 = tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
W1 shape = torch.Size([3, 2])
Weights for H2 = tensor([[-1.6822],
        [ 0.3177]])
W2 shape = torch.Size([2, 1])
Bias for H1 = tensor([[0.1328, 0.1373]])
B1 shape = torch.Size([1, 2])
Bias for H2 = tensor([[0.2405]])
B2 shape = torch.Size([1, 1])


In [4]:
h1 = activation(torch.mm(features, W1) + B1)
y = activation(torch.mm(h1, W2) + B2)
print("output =", y)

output = tensor([[0.3171]])


# Numpy to Torch and back

In [0]:
import numpy as np

In [6]:
a = np.random.rand(4,3)
a

array([[0.92574991, 0.78684266, 0.23094331],
       [0.59339351, 0.29331758, 0.73476862],
       [0.47561707, 0.85878474, 0.09992052],
       [0.3773617 , 0.80045517, 0.00223692]])

In [7]:
b = torch.from_numpy(a)
b

tensor([[0.9257, 0.7868, 0.2309],
        [0.5934, 0.2933, 0.7348],
        [0.4756, 0.8588, 0.0999],
        [0.3774, 0.8005, 0.0022]], dtype=torch.float64)

In [8]:
b.numpy()

array([[0.92574991, 0.78684266, 0.23094331],
       [0.59339351, 0.29331758, 0.73476862],
       [0.47561707, 0.85878474, 0.09992052],
       [0.3773617 , 0.80045517, 0.00223692]])

In [9]:
b.mul_(2)

tensor([[1.8515, 1.5737, 0.4619],
        [1.1868, 0.5866, 1.4695],
        [0.9512, 1.7176, 0.1998],
        [0.7547, 1.6009, 0.0045]], dtype=torch.float64)

In [10]:
a

array([[1.85149982, 1.57368531, 0.46188661],
       [1.18678701, 0.58663517, 1.46953723],
       [0.95123414, 1.71756947, 0.19984103],
       [0.7547234 , 1.60091035, 0.00447384]])